2021-01-28 22:47:56,276 INFO  [main] root: Disconnected from KVServer
2021-01-28 22:48:14,998 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 22:53:39,008 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:03:17,524 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:03:19,551 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:03:36,264 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:03:38,273 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:06:46,064 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:40:16,890 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:41:45,415 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:42:38,318 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:42:40,353 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:42:56,996 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:42:59,001 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:44:01,449 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:44:03,467 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:44:20,177 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:44:22,182 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:44:54,093 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:44:56,128 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:45:12,799 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:45:14,804 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:51:12,973 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:51:29,655 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:51:31,667 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:52:45,080 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:53:01,829 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:53:03,835 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:54:38,666 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:57:28,995 INFO  [main] root: Disconnected from KVServer
2021-01-28 23:57:47,605 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-28 23:57:47,613 INFO  [main] root: Disconnected from KVServer
2021-01-29 00:00:51,594 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 00:00:51,606 INFO  [main] root: Disconnected from KVServer
2021-01-29 00:01:30,688 INFO  [main] root: Disconnected from KVServer
2021-01-29 00:01:32,713 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 00:12:33,197 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 00:12:51,880 INFO  [main] root: Disconnected from KVServer
2021-01-29 00:14:51,835 INFO  [main] root: Disconnected from KVServer
2021-01-29 00:16:22,997 INFO  [main] root: Disconnected from KVServer
2021-01-29 00:16:25,017 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:41)
	at app_kvClient.KVClient.newConnection(KVClient.java:47)
	at app_kvClient.KVClient.handleCommand(KVClient.java:144)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 00:16:43,759 INFO  [main] root: Disconnected from KVServer
2021-01-29 01:58:33,313 INFO  [main] root: client running
2021-01-29 01:58:35,332 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:39)
	at app_kvClient.KVClient.newConnection(KVClient.java:64)
	at app_kvClient.KVClient.handleCommand(KVClient.java:183)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 01:58:51,984 INFO  [main] root: client running
2021-01-29 01:58:54,008 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:39)
	at app_kvClient.KVClient.newConnection(KVClient.java:64)
	at app_kvClient.KVClient.handleCommand(KVClient.java:183)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 02:10:06,905 INFO  [main] root: client running
2021-01-29 02:10:06,915 INFO  [main] root: Disconnected from KVServer
2021-01-29 02:10:08,939 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:39)
	at app_kvClient.KVClient.newConnection(KVClient.java:64)
	at app_kvClient.KVClient.handleCommand(KVClient.java:183)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 02:11:11,313 INFO  [main] root: client running
2021-01-29 02:11:11,323 INFO  [main] root: Disconnected from KVServer
2021-01-29 02:11:13,344 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:39)
	at app_kvClient.KVClient.newConnection(KVClient.java:64)
	at app_kvClient.KVClient.handleCommand(KVClient.java:183)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 02:11:29,950 INFO  [main] root: client running
2021-01-29 02:11:31,971 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:39)
	at app_kvClient.KVClient.newConnection(KVClient.java:64)
	at app_kvClient.KVClient.handleCommand(KVClient.java:183)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 02:11:31,975 INFO  [main] root: Disconnected from KVServer
2021-01-29 02:26:50,745 INFO  [main] root: client running
2021-01-29 02:27:26,276 INFO  [main] root: Connection established
2021-01-29 02:27:26,277 INFO  [main] root: Connected to KVServer
2021-01-29 02:28:03,668 INFO  [main] root: Sent message:	 'PUT Johnathon Martin'
2021-01-29 02:28:03,669 INFO  [main] root: Sent request for PUT: <Johnathon,Martin>
2021-01-29 02:28:03,703 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <Johnathon          ,Martin>
2021-01-29 02:28:03,703 INFO  [Thread-0] root: Put: <Johnathon          ,Martin>
2021-01-29 02:28:47,733 INFO  [main] root: Sent message:	 'PUT hello server'
2021-01-29 02:28:47,733 INFO  [main] root: Sent request for PUT: <hello,server>
2021-01-29 02:28:47,738 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <hello              ,server>
2021-01-29 02:28:47,738 INFO  [Thread-0] root: Put: <hello              ,server>
2021-01-29 02:28:52,965 INFO  [main] root: Sent message:	 'PUT its late'
2021-01-29 02:28:52,965 INFO  [main] root: Sent request for PUT: <its,late>
2021-01-29 02:28:52,972 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <its                ,late>
2021-01-29 02:28:52,972 INFO  [Thread-0] root: Put: <its                ,late>
2021-01-29 02:28:57,064 ERROR [main] root: Error getting value for key: its
java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
	at shared.messages.TextMessage.<init>(TextMessage.java:38)
	at client.KVStore.get(KVStore.java:197)
	at app_kvClient.KVClient.handleCommand(KVClient.java:233)
	at app_kvClient.KVClient.run(KVClient.java:97)
	at app_kvClient.KVClient.main(KVClient.java:45)
2021-01-29 02:34:36,058 INFO  [main] root: try to close connection ...
2021-01-29 02:34:36,059 INFO  [main] root: tearing down the connection ...
2021-01-29 02:34:36,062 INFO  [main] root: connection closed!
2021-01-29 02:34:36,063 INFO  [main] root: Connection terminated: localhost / 5000
2021-01-29 02:36:05,128 INFO  [main] root: client running
2021-01-29 02:37:07,087 INFO  [main] root: Connection established
2021-01-29 02:37:07,088 INFO  [main] root: Connected to KVServer
2021-01-29 02:37:18,865 INFO  [main] root: Sent message:	 'PUT dont add'
2021-01-29 02:37:18,865 INFO  [main] root: Sent request for PUT: <dont,add>
2021-01-29 02:37:18,886 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <dont               ,add>
2021-01-29 02:37:18,886 INFO  [Thread-0] root: Put: <dont               ,add>
2021-01-29 02:37:21,225 ERROR [main] root: Error getting value for key: dont
java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
	at shared.messages.TextMessage.<init>(TextMessage.java:38)
	at client.KVStore.get(KVStore.java:197)
	at app_kvClient.KVClient.handleCommand(KVClient.java:233)
	at app_kvClient.KVClient.run(KVClient.java:97)
	at app_kvClient.KVClient.main(KVClient.java:45)
2021-01-29 02:39:17,889 INFO  [main] root: Sent message:	 'PUT test 123'
2021-01-29 02:39:17,889 INFO  [main] root: Sent request for PUT: <test,123>
2021-01-29 02:39:17,895 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <test               ,123>
2021-01-29 02:39:17,895 INFO  [Thread-0] root: Put: <test               ,123>
2021-01-29 02:41:14,740 ERROR [main] root: Error getting value for key: test
java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
	at shared.messages.TextMessage.<init>(TextMessage.java:38)
	at client.KVStore.get(KVStore.java:197)
	at app_kvClient.KVClient.handleCommand(KVClient.java:233)
	at app_kvClient.KVClient.run(KVClient.java:97)
	at app_kvClient.KVClient.main(KVClient.java:45)
2021-01-29 02:42:54,271 INFO  [main] root: client running
2021-01-29 02:43:02,983 INFO  [main] root: Connection established
2021-01-29 02:43:02,984 INFO  [main] root: Connected to KVServer
2021-01-29 02:43:18,225 INFO  [main] root: Sent message:	 'PUT testing 1234'
2021-01-29 02:43:18,225 INFO  [main] root: Sent request for PUT: <testing,1234>
2021-01-29 02:43:18,254 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <testing            ,1234>
2021-01-29 02:43:18,255 INFO  [Thread-0] root: Put: <testing            ,1234>
2021-01-29 02:43:30,303 INFO  [main] root: Sent message:	 'GET testing'
2021-01-29 02:43:30,303 INFO  [main] root: Sent request for GET: testing
2021-01-29 02:43:30,306 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <testing            ,1234>
2021-01-29 02:43:30,306 INFO  [Thread-0] root: Got: <testing            ,1234>
2021-01-29 02:44:00,236 INFO  [main] root: Sent message:	 'PUT testing '
2021-01-29 02:44:00,236 INFO  [main] root: Sent request for PUT: <testing,>
2021-01-29 02:44:00,242 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <testing            ,>
2021-01-29 02:44:06,505 INFO  [main] root: Sent message:	 'GET testing'
2021-01-29 02:44:06,505 INFO  [main] root: Sent request for GET: testing
2021-01-29 02:44:06,508 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <testing            ,>
2021-01-29 02:44:06,508 INFO  [Thread-0] root: Got: <testing            ,>
2021-01-29 02:46:01,240 INFO  [main] root: try to close connection ...
2021-01-29 02:46:01,240 INFO  [main] root: tearing down the connection ...
2021-01-29 02:46:01,241 INFO  [main] root: connection closed!
2021-01-29 02:46:01,241 INFO  [main] root: Connection terminated: localhost / 5000
2021-01-29 02:46:45,153 INFO  [main] root: client running
2021-01-29 02:47:37,910 INFO  [main] root: Connection established
2021-01-29 02:47:37,910 INFO  [main] root: Connected to KVServer
2021-01-29 02:47:58,149 INFO  [main] root: Sent message:	 'PUT hiii 1234'
2021-01-29 02:47:58,149 INFO  [main] root: Sent request for PUT: <hiii,1234>
2021-01-29 02:47:58,168 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <hiii               ,1234>
2021-01-29 02:47:58,169 INFO  [Thread-0] root: Put: <hiii               ,1234>
2021-01-29 02:48:01,453 INFO  [main] root: Sent message:	 'GET hiii'
2021-01-29 02:48:01,454 INFO  [main] root: Sent request for GET: hiii
2021-01-29 02:48:01,457 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <hiii               ,1234>
2021-01-29 02:48:01,458 INFO  [Thread-0] root: Got: <hiii               ,1234>
2021-01-29 02:48:07,912 INFO  [main] root: Sent message:	 'PUT hiii '
2021-01-29 02:48:07,912 INFO  [main] root: Sent request for PUT: <hiii,>
2021-01-29 02:48:07,916 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <hiii               ,>
2021-01-29 02:48:15,650 INFO  [main] root: Sent message:	 'GET hiii'
2021-01-29 02:48:15,650 INFO  [main] root: Sent request for GET: hiii
2021-01-29 02:48:15,652 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <hiii               ,>
2021-01-29 02:48:15,652 INFO  [Thread-0] root: Got: <hiii               ,>
2021-01-29 02:55:00,996 INFO  [main] root: try to close connection ...
2021-01-29 02:55:00,996 INFO  [main] root: tearing down the connection ...
2021-01-29 02:55:00,997 INFO  [main] root: connection closed!
2021-01-29 02:55:00,998 INFO  [main] root: Connection terminated: localhost / 5000
2021-01-29 02:55:45,047 INFO  [main] root: client running
2021-01-29 02:56:03,231 INFO  [main] root: Connection established
2021-01-29 02:56:03,231 INFO  [main] root: Connected to KVServer
2021-01-29 02:57:12,370 INFO  [main] root: Sent message:	 'PUT test4 1234'
2021-01-29 02:57:12,370 INFO  [main] root: Sent request for PUT: <test4,1234>
2021-01-29 02:57:12,392 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <test4              ,1234>
2021-01-29 02:57:12,392 INFO  [Thread-0] root: Put: <test4              ,1234>
2021-01-29 02:57:16,147 INFO  [main] root: Sent message:	 'GET test4'
2021-01-29 02:57:16,147 INFO  [main] root: Sent request for GET: test4
2021-01-29 02:57:16,150 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <test4              ,1234>
2021-01-29 02:57:16,150 INFO  [Thread-0] root: Got: <test4              ,1234>
2021-01-29 02:57:31,308 INFO  [main] root: Sent message:	 'PUT test4 '
2021-01-29 02:57:31,308 INFO  [main] root: Sent request for PUT: <test4,>
2021-01-29 02:57:31,312 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <test4              ,>
2021-01-29 02:57:38,739 INFO  [main] root: Sent message:	 'GET test4'
2021-01-29 02:57:38,739 INFO  [main] root: Sent request for GET: test4
2021-01-29 02:57:38,741 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <test4              ,>
2021-01-29 02:57:38,742 INFO  [Thread-0] root: Got: <test4              ,>
2021-01-29 02:58:52,000 ERROR [Thread-0] root: Connection lost!
2021-01-29 02:58:52,000 INFO  [Thread-0] root: tearing down the connection ...
2021-01-29 02:58:52,000 INFO  [Thread-0] root: connection closed!
2021-01-29 02:58:52,001 ERROR [Thread-0] root: Connection terminated: localhost / 5000
2021-01-29 02:59:13,358 INFO  [main] root: client running
2021-01-29 02:59:23,583 INFO  [main] root: Connection established
2021-01-29 02:59:23,584 INFO  [main] root: Connected to KVServer
2021-01-29 02:59:31,091 INFO  [main] root: Sent message:	 'PUT please work'
2021-01-29 02:59:31,091 INFO  [main] root: Sent request for PUT: <please,work>
2021-01-29 02:59:31,111 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <please             ,work>
2021-01-29 02:59:31,112 INFO  [Thread-0] root: Put: <please             ,work>
2021-01-29 02:59:37,561 INFO  [main] root: Sent message:	 'GET please'
2021-01-29 02:59:37,562 INFO  [main] root: Sent request for GET: please
2021-01-29 02:59:37,566 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <please             ,work>
2021-01-29 02:59:37,566 INFO  [Thread-0] root: Got: <please             ,work>
2021-01-29 02:59:48,575 INFO  [main] root: Sent message:	 'PUT please '
2021-01-29 02:59:48,576 INFO  [main] root: Sent request for PUT: <please,>
2021-01-29 02:59:48,581 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <please             ,>
2021-01-29 02:59:52,541 INFO  [main] root: Sent message:	 'GET please'
2021-01-29 02:59:52,542 INFO  [main] root: Sent request for GET: please
2021-01-29 02:59:52,544 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <please             ,>
2021-01-29 02:59:52,544 ERROR [Thread-0] root: Error with Get request for key: please             
2021-01-29 03:06:14,679 INFO  [main] root: client running
2021-01-29 03:06:16,701 ERROR [main] root: I/O error when creating socket on port: 6000
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:574)
	at java.base/sun.nio.ch.Net.connect(Net.java:563)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at client.KVStore.connect(KVStore.java:38)
	at app_kvClient.KVClient.newConnection(KVClient.java:64)
	at app_kvClient.KVClient.handleCommand(KVClient.java:184)
	at testing.AdditionalTest.test_client_connect(AdditionalTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
2021-01-29 03:06:16,707 INFO  [main] root: Disconnected from KVServer
2021-01-29 03:06:35,398 INFO  [main] root: client running
2021-01-29 03:06:35,406 INFO  [main] root: Disconnected from KVServer
2021-01-29 03:20:32,515 INFO  [main] root: client running
2021-01-29 03:20:32,520 INFO  [Thread-0] root: Initialize server ...
2021-01-29 03:20:32,525 INFO  [Thread-0] root: Server listening on port: 6000
2021-01-29 03:20:32,528 INFO  [main] root: Connection established
2021-01-29 03:20:32,528 INFO  [main] root: Connected to KVServer
2021-01-29 03:20:32,529 INFO  [Thread-2] root: Initialize server ...
2021-01-29 03:20:32,529 DEBUG [Thread-3] root: receiving message
2021-01-29 03:20:32,530 INFO  [Thread-2] root: Server listening on port: 3000
2021-01-29 03:20:32,539 INFO  [Thread-0] root: Connected to kubernetes.docker.internal on port 54542
2021-01-29 03:20:32,541 INFO  [Thread-4] root: Initialize server ...
2021-01-29 03:20:32,543 ERROR [Thread-4] root: Error! Cannot open server socket:
2021-01-29 03:20:32,543 ERROR [Thread-4] root: Port 3000 is already bound!
2021-01-29 03:20:32,543 INFO  [Thread-4] root: Server stopped.
2021-01-29 03:20:32,549 INFO  [main] root: Disconnected from KVServer
2021-01-29 03:20:32,553 INFO  [Thread-5] root: Initialize server ...
2021-01-29 03:20:32,554 ERROR [Thread-5] root: Error! Cannot open server socket:
2021-01-29 03:20:32,554 ERROR [Thread-5] root: Port 3000 is already bound!
2021-01-29 03:20:32,554 INFO  [Thread-5] root: Server stopped.
2021-01-29 03:20:35,528 INFO  [main] root: client running
2021-01-29 03:20:35,530 INFO  [Thread-20] root: Initialize server ...
2021-01-29 03:20:35,531 INFO  [Thread-20] root: Server listening on port: 6000
2021-01-29 03:20:36,031 INFO  [main] root: Connection established
2021-01-29 03:20:36,032 DEBUG [Thread-22] root: receiving message
2021-01-29 03:20:36,032 INFO  [main] root: Connected to KVServer
2021-01-29 03:20:36,032 INFO  [Thread-20] root: Connected to kubernetes.docker.internal on port 54559
2021-01-29 03:52:39,149 INFO  [main] root: client running
2021-01-29 03:52:39,151 INFO  [main] root: Disconnected from KVServer
2021-01-29 03:52:39,152 INFO  [Thread-1] root: Initialize server ...
2021-01-29 03:52:39,153 ERROR [Thread-1] root: Error! Cannot open server socket:
2021-01-29 03:52:39,153 ERROR [Thread-1] root: Port 3000 is already bound!
2021-01-29 03:52:39,153 INFO  [Thread-1] root: Server stopped.
2021-01-29 03:52:39,155 INFO  [Thread-2] root: Initialize server ...
2021-01-29 03:52:39,155 ERROR [Thread-2] root: Error! Cannot open server socket:
2021-01-29 03:52:39,155 ERROR [Thread-2] root: Port 3000 is already bound!
2021-01-29 03:52:39,155 INFO  [Thread-2] root: Server stopped.
2021-01-29 03:52:39,162 INFO  [Thread-3] root: Initialize server ...
2021-01-29 03:52:39,163 INFO  [Thread-3] root: Server listening on port: 6000
2021-01-29 03:52:39,166 INFO  [main] root: Connection established
2021-01-29 03:52:39,166 INFO  [main] root: Connected to KVServer
2021-01-29 03:52:39,167 DEBUG [Thread-5] root: receiving message
2021-01-29 03:52:39,179 INFO  [Thread-3] root: Connected to kubernetes.docker.internal on port 56038
2021-01-29 03:53:01,769 INFO  [main] root: client running
2021-01-29 03:53:11,443 INFO  [main] root: Connection established
2021-01-29 03:53:11,443 INFO  [main] root: Connected to KVServer
2021-01-29 03:53:57,836 INFO  [main] root: Sent message:	 'PUT jmartin1 test'
2021-01-29 03:53:57,836 INFO  [main] root: Sent request for PUT: <jmartin1,test>
2021-01-29 03:53:57,860 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <jmartin1,test>
2021-01-29 03:53:57,860 INFO  [Thread-0] root: Put: <jmartin1,test>
2021-01-29 03:54:08,506 INFO  [main] root: Sent message:	 'GET jmartin1'
2021-01-29 03:54:08,506 INFO  [main] root: Sent request for GET: jmartin1
2021-01-29 03:54:08,510 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <jmartin1,test>
2021-01-29 03:54:08,510 INFO  [Thread-0] root: Got: <jmartin1,test>
2021-01-29 03:54:21,554 INFO  [main] root: Sent message:	 'PUT jmartin1 '
2021-01-29 03:54:21,554 INFO  [main] root: Sent request for PUT: <jmartin1,>
2021-01-29 03:54:21,558 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <jmartin1,>
2021-01-29 03:54:26,766 INFO  [main] root: Sent message:	 'GET jmartin1'
2021-01-29 03:54:26,767 INFO  [main] root: Sent request for GET: jmartin1
2021-01-29 03:54:26,770 INFO  [Thread-0] root: RECEIVE 	<127.0.0.1:5000>: <jmartin1,>
2021-01-29 03:54:26,771 ERROR [Thread-0] root: Error with Get request for key: jmartin1
2021-01-29 13:55:18,733 INFO  [main] root: client running
2021-01-29 13:55:18,737 INFO  [Thread-4] root: Initialize server ...
2021-01-29 13:55:18,737 ERROR [Thread-4] root: Error! Cannot open server socket:
2021-01-29 13:55:18,738 ERROR [Thread-4] root: Port 3000 is already bound!
2021-01-29 13:55:18,738 INFO  [Thread-4] root: Server stopped.
2021-01-29 13:55:18,750 INFO  [Thread-5] root: Initialize server ...
2021-01-29 13:55:18,751 ERROR [Thread-5] root: Error! Cannot open server socket:
2021-01-29 13:55:18,751 ERROR [Thread-5] root: Port 3000 is already bound!
2021-01-29 13:55:18,752 INFO  [Thread-5] root: Server stopped.
2021-01-29 13:55:18,759 INFO  [Thread-6] root: Initialize server ...
2021-01-29 13:55:18,760 ERROR [Thread-6] root: Error! Cannot open server socket:
2021-01-29 13:55:18,760 ERROR [Thread-6] root: Port 3000 is already bound!
2021-01-29 13:55:18,760 INFO  [Thread-6] root: Server stopped.
2021-01-29 13:55:21,858 INFO  [main] root: client running
2021-01-29 13:55:21,861 INFO  [main] root: Disconnected from KVServer
2021-01-29 13:55:21,864 INFO  [Thread-8] root: Initialize server ...
2021-01-29 13:55:21,865 INFO  [Thread-8] root: Server listening on port: 15000
2021-01-29 13:55:22,366 INFO  [main] root: Connection established
2021-01-29 13:55:22,366 INFO  [Thread-8] root: Connected to kubernetes.docker.internal on port 65442
2021-01-29 13:55:22,366 DEBUG [Thread-9] root: receiving message
2021-01-29 13:55:22,366 INFO  [main] root: Connected to KVServer
2021-01-29 13:55:22,369 INFO  [Thread-10] root: Initialize server ...
2021-01-29 13:55:22,370 INFO  [Thread-10] root: Server listening on port: 3000
2021-01-29 13:55:22,373 INFO  [Thread-11] root: Initialize server ...
2021-01-29 13:55:22,374 ERROR [Thread-11] root: Error! Cannot open server socket:
2021-01-29 13:55:22,374 ERROR [Thread-11] root: Port 3000 is already bound!
2021-01-29 13:55:22,374 INFO  [Thread-11] root: Server stopped.
2021-01-29 13:55:22,380 INFO  [Thread-12] root: Initialize server ...
2021-01-29 13:55:22,381 ERROR [Thread-12] root: Error! Cannot open server socket:
2021-01-29 13:55:22,381 ERROR [Thread-12] root: Port 3000 is already bound!
2021-01-29 13:55:22,381 INFO  [Thread-12] root: Server stopped.
2021-01-29 13:55:22,393 INFO  [Thread-13] root: Initialize server ...
2021-01-29 13:55:22,394 ERROR [Thread-13] root: Error! Cannot open server socket:
2021-01-29 13:55:22,394 ERROR [Thread-13] root: Port 3000 is already bound!
2021-01-29 13:55:22,394 INFO  [Thread-13] root: Server stopped.
2021-01-29 13:55:22,402 INFO  [Thread-14] root: Initialize server ...
2021-01-29 13:55:22,403 ERROR [Thread-14] root: Error! Cannot open server socket:
2021-01-29 13:55:22,404 ERROR [Thread-14] root: Port 3000 is already bound!
2021-01-29 13:55:22,404 INFO  [Thread-14] root: Server stopped.
